# The integration deploys to cloud every time changes are pushed to deployment branch

# Environment Variables: https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows

name: Continuous Integration
on:
  push:
    branches: deployment
  pull_request:
    branches: deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
      - name: Set current date as env variable
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Run Makefile deploy
        run: |
          make build-commit-donpush v=${{ steps.date.outputs.date }}
          make ft-push

