# The integration deploys to cloud every time changes are pushed to deployment branch

# Environment Variables: https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows

# For Weekly Sunday Update: name: Continuous Integration
#     - cron: "0 0 * * 0" # This will run the workflow at midnight (00:00) every Sunday

# For Daily Updates
#     - cron: "0 0 * * *"
  

name: Continuous Integration
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: deployment
  pull_request:
    branches: deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
      - name: Run Makefile deploy
        run: |
          git config --global user.name "nenewang"
          make build-commit-donpush
          make ft-configpush
