# The integration deploys to cloud every time changes are pushed to deployment branch

name: Continuous Integration
on:
  push:
    branches: deployment
  pull_request:
    branches: deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2        
      - name: Run Makefile deploy
        run: make say_hello ${{ steps.date.outputs.date }}

